# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TimetableApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FMDB'
  # Pods for TimetableApp

  target 'TimetableAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TimetableAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
